[package]
name = "grep-command"
version = "0.1.0"
authors = ["rajat merwade <rajat.rajeshmerwade@harman.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "grep"
path = "src/grep_main.rs"
